language: java
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - net-tools
notifications:
  slack:
    on_success: always
    secure: aC4TRo2EiPb0LUA5L1+7JhLzmSFw8Uiqzr3ycDpMc+PMQLM9pOKxZ1OckJZIQBcCnmgcnTMuNXrcuZAY0GIwJ65hu8uRxJGjLROb0KsVCvuJnvBdAjE+MlPIHbegyRA9YLupdRUdpuHAtYmy/Fdub33SHZ9ZXYpiOfYVFfaUpSk=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jyLXwq//aSLkGongM7/Sh2yJ6/SxlZ4kJvf1b4NgFm4yK2Ut8Lpf0+kl7oBctoFEZdIGLt65yJzU7u4g2OS3WGMz07TJdEHuvTc59GOG6tIPu9F+ROnGlDZCJOLEwZ4cmTsJEUK0b7xvo2S8OKHTQtYiiLQFyrmRL90POmxrMtjA77LqcpFfg9aa1DqKofzBd5qhpAhEfYc0iTKOkb6ZaPtcgKHXLpeScwZORpKrAI2NQg7MJ3hTcH0BjGgP/OpT52a36mRur4EE5puWwnIxlbUpIYjSfCIEA8OyIA1OFX3G31v9oo9kRdP8Kbiu5w2GxCHO+XuRN4ehAld5d8OrmPLdQLShgiSel/1Ekr72WClF6XRO1q68YLqzCVORYJmkpDX4qy+5Ipnhvw5RlpjyPFnCHGFriaIbdxqUBSJC6gxKnQWfimuu2byDmdcOmV28MM7xvsi9UVHC/Le9QqW1bsHkzKP/CJ1dNzNYddFpZO4CZjkd5FXXg+83G52JIUxYmRbo2LA0KybuO1uQYEUeb6WKyWplvVh4ekn0lMGb4ME/Lor4aVeWF+UWlGZQRaBi+Fk2col1r2tXb/RRTkOI1r3hp8IhZSgkKmGQkiNoa0FONZwYu7XmXI+rAG21h26GaiBJO1P3mLq18jnEI5ByTWm2PWhYNQAtAFsYA7pSczU=
  file: target/Curly-2.0-SNAPSHOT.jar
  on:
    repo: Adobe-Consulting-Services/curly
    tags: true